#!/usr/bin/env python
#
# Script to build the files found in this directory.
#------------------------------------------------------------------------------
import os, subprocess
Import('daqana_env')
Import('stntuple_helper')
#------------------------------------------------------------------------------
# 2016-10-10: STNTUPLE link: add ROOT 'EG' library after 'Physics' library
#------------------------------------------------------------------------------
def local_build():
    local_env = daqana_env.Clone()

    babarlibs = local_env['BABARLIBS']
    rootlibs  = local_env['ROOTLIBS']

    if ( not ("EG" in rootlibs)): rootlibs.insert(rootlibs.index("Physics")+1,"EG");
    if ( not ("Geom" in rootlibs)): rootlibs.insert(rootlibs.index("Physics")+1,"Geom");

    helper = stntuple_helper(local_env);
#------------------------------------------------------------------------------
# work around a bug in fhiclcpp 4.19.00-4.19.01:
# don't generate the ROOT dictionary for MuHitDisplay module for those versions
#------------------------------------------------------------------------------
    cmd = "spack find fhicl-cpp | grep fhicl-cpp | awk -F @ '{print $2}'"
    p = subprocess.Popen(cmd,
                         executable="/bin/bash",
                         shell=True,
                         stderr=subprocess.PIPE,
                         stdout=subprocess.PIPE,
                         encoding="utf-8")
    (out, err) = p.communicate();
    fhiclcpp_ver=out.strip();
    # print(f'out_2:{out} len(out):{len(out)} fhiclcpp_ver:{fhiclcpp_ver}')
    
    skip_dicts = []
    if (fhiclcpp_ver == '4.19.00') or (fhiclcpp_ver == '4.19.01'):
        skip_dicts.append('TrkFragmentAna_module_linkdef.h')

    helper.handle_dictionaries(skip_list=skip_dicts);

    libs      = [                
                  'Stntuple_loop',
                  'Stntuple_base',
                  'Stntuple_val',
                  'daqana_obj',
#
                  'mu2e_CalPatRec',
                  'mu2e_TrkReco',
                  'mu2e_TrkHitReco',
                  'mu2e_TrackerConditions',
                  'mu2e_Mu2eBTrk',
                  'mu2e_GeometryService',
                  'mu2e_ConditionsService',
                  'mu2e_Mu2eUtilities',
                  'mu2e_GeneralUtilities',
                  'mu2e_CaloCluster',
                  'mu2e_CalorimeterGeom',
                  'mu2e_CRVResponse',
                  'mu2e_MCDataProducts',
                  'mu2e_RecoDataProducts',
                  'mu2e_BTrkData',
                  'mu2e_BFieldGeom',
                  'mu2e_DataProducts',
                  # 'mu2e_Mu2eInterfaces',
                  'mu2e_DbService',
                  'mu2e_DbTables',
                 'KinKal_Trajectory',
                 'KinKal_General',
                  babarlibs,
                  'art_Framework_Core',
                  'art_Framework_Principal',
                  'art_Framework_Services_Registry',
                  'art_root_io_tfile_support',
                  'art_root_io_TFileService',
                  'art_Framework_Services_Optional_RandomNumberGenerator_service',
                  'art_Persistency_Common',
                  'art_Persistency_Provenance',
                  'art_Utilities',
                  'canvas',
                  'MF_MessageLogger',
                  'fhiclcpp',
                  'fhiclcpp_types',
                  'tbb',
                  'cetlib',
                  'cetlib_except',
                  'CLHEP',
                  rootlibs,
                  # extrarootlibs,
                  'xerces-c',
                  'boost_filesystem',
                  'pthread',
                  'hep_concurrency',
                  'artdaq-core-mu2e_Data',
                  'artdaq-core_Data',
                  'tracelib'
              ];

    list_of_cc_files = Glob('*.cc'       , strings=True)
    list_of_modules  = Glob('*_module.cc', strings=True)
    list_of_plugins  = Glob('*_tool.cc'  , strings=True)
    skip_list        = list_of_modules+list_of_plugins

    helper.build_libs(list_of_cc_files,skip_list,libs);
    helper.build_modules(list_of_modules+list_of_plugins,[],libs=libs,skip_dict_list=skip_dicts)
#------------------------------------------------------------------------------
local_build()

# print "tmpdir:"+env['TMP_LIB_DIR']
